### ISSUE TITLE
Issue about Basel dataset

### ISSUE THREAD

**Issue by heyhola** [xhelenfu/DMGN_Survival_Prediction#3]
Hello Xiaohang,
Thanks for the great work ! I tried to reproduce the survival prediction results  in your paper, though I browse the Basel dataset download from the zenodo, I can't find the PVs about the patient, except age and ER.status, could you tell you how to get the clinical data in the Basel dataset?
Best wishes!
Siqi

**Comment by xhelenfu** [comment]
Hi Siqi,
The treatment information may be found in column 'Post-surgeryTx' in Basel_PatientMetadata.csv. Expression data may be found in Data_publication/BaselTMA/SC_dat.csv in SingleCell_and_Metadata.zip. Data are available through https://zenodo.org/record/3518284 
Best regards,
Xiaohang

**Comment by heyhola** [comment]
Thank you for your reply, I got treatment information and part of expression data, but I can't find about HER2 yet, could you tell you how to get the HER2 in the file?
Best wishes!
Siqi
